
# -----POST CRUD-----
### Add a new post
POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "John Doe",
    "title": "My first post",
    "content": "Hello world!"
}

### Get All Posts
GET http://localhost:3000/post


### Get a Post by ID
GET http://localhost:3000/post/6745c3f469c604def9dec936

### 
GET http://localhost:3000/post?sender=John%20Doe

### Update a post
PUT http://localhost:3000/post/6745c3f469c604def9dec936
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post."
}

###
DELETE http://localhost:3000/post/6745c3f469c604def9dec936

# -----POST CRUD-----


# -----COMMENT CRUD-----
### Create a Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
  "content": "This is a comment",
  "sender": "lolol",
  "postId": "6745c3f469c604def9dec936"
}

### Get All comments
GET http://localhost:3000/comment

### Get Comment By ID
GET http://localhost:3000/comment/6745cacabce2f164d9494634

### Get All Comments By Sender
GET http://localhost:3000/comment?sender=lolol

### Get All Comments By PostId
GET http://localhost:3000/comment?postId=6745c3f469c604def9dec936

### Update a Comment
PUT http://localhost:3000/comment/6745cacabce2f164d9494634
Content-Type: application/json

{
  "content": "Updated comment content1"
}

### Delete a Comment
DELETE http://localhost:3000/comment/6745cacabce2f164d9494634
# -----POST CRUD-----
