

### Add a new post
POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "John Doe",
    "title": "My first post",
    "content": "Hello world!"
}

### Get All Posts
GET http://localhost:3000/post


### Get a Post by ID
GET http://localhost:3000/post/6742325ad92c5574b3cbc2ce

### 
GET http://localhost:3000/post?sender=John%20Doe

### Update a post
PUT http://localhost:3000/post/6742325ad92c5574b3cbc2ce
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post."
}

###
DELETE http://localhost:3000/post/674239be91bde9348df4f3c0